version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      next:
        patterns:
          - "next"
          - "@next/*"
          - "eslint-config-next"

  - package-ecosystem: "gomod"
    directory: "/apps/api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/apps/web"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/apps/admin"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
