run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nilerr
    - noctx
    - revive
    - staticcheck
    - typecheck
    - unparam
    - unused

linters-settings:
  gosec:
    excludes:
      - G104
      - G404
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - unparam
